package com.fusesource.camel_cxf_corba_test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Progress FUSE Services Framework 2.2.10-fuse-00-00
 * Wed Dec 29 12:15:47 CET 2010
 * Generated source version: 2.2.10-fuse-00-00
 * 
 */


@WebServiceClient(name = "GridCORBAService", 
                  wsdlLocation = "file:grid.wsdl",
                  targetNamespace = "http://fusesource.com/camel_cxf_corba_test") 
public class GridCORBAService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://fusesource.com/camel_cxf_corba_test", "GridCORBAService");
    public final static QName GridCORBAPort = new QName("http://fusesource.com/camel_cxf_corba_test", "GridCORBAPort");
    static {
        URL url = null;
        try {
            url = new URL("file:grid.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:grid.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GridCORBAService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GridCORBAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GridCORBAService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns Grid
     */
    @WebEndpoint(name = "GridCORBAPort")
    public Grid getGridCORBAPort() {
        return super.getPort(GridCORBAPort, Grid.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Grid
     */
    @WebEndpoint(name = "GridCORBAPort")
    public Grid getGridCORBAPort(WebServiceFeature... features) {
        return super.getPort(GridCORBAPort, Grid.class, features);
    }

}
